package program.view;

import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;

/**
 * Holds the main view for the program
 */
public class ProgramView extends JFrame {

    private IProgramView2ModelAdapter v2m;
    private JPanel pnlMain;
    private JPanel pnlControls;
    private JSpinner spnWidth;
    private JSpinner spnHeight;
    private JLabel lblDimensions;
    private JLabel lblX;
    private JButton btnCreateImage;
    private JLabel lblImage;

    public ProgramView(IProgramView2ModelAdapter v2m) {
        this.v2m = v2m;

        this.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        $$$setupUI$$$();
    }

    /**
     * Perfroms all start up tasks associated with the view.
     */
    public void start() {

        this.add(pnlMain);

        this.setVisible(true);
        this.pack();
    }

    /**
     * Displays the completed image for the user to see
     *
     * @param image The image for the user to view
     */
    public void displayImage(BufferedImage image) {
        lblImage.setIcon(new ImageIcon(image.getScaledInstance(300, -1, Image.SCALE_SMOOTH)));
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        pnlMain = new JPanel();
        pnlMain.setLayout(new BorderLayout(0, 0));
        pnlMain.setBackground(new Color(-3748656));
        pnlControls = new JPanel();
        pnlControls.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        pnlMain.add(pnlControls, BorderLayout.SOUTH);
        lblDimensions = new JLabel();
        lblDimensions.setText("Dimensions:");
        pnlControls.add(lblDimensions);
        spnWidth = new JSpinner();
        spnWidth.setToolTipText("Choose the width of your background");
        pnlControls.add(spnWidth);
        lblX = new JLabel();
        lblX.setText("X");
        pnlControls.add(lblX);
        spnHeight = new JSpinner();
        spnHeight.setToolTipText("Choose the height of your background");
        pnlControls.add(spnHeight);
        btnCreateImage = new JButton();
        btnCreateImage.setText("Create");
        btnCreateImage.setToolTipText("Create a random image of the given size");
        pnlControls.add(btnCreateImage);
        lblImage = new JLabel();
        lblImage.setText("");
        pnlMain.add(lblImage, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pnlMain;
    }
}
